### PR TITLE
Paper about "The Pomodoro Technique" is missing

### PR DESCRIPTION
**Pull request by Zilnik**
Removed broken link (paper Pomodoro Technique)

### CODE REVIEW

**Comment by joebew42** [comment]
Hi @Zilnik ,

Thanks for your help! 🌟

I didn't notice the paper was missing. Good catch! I guess we should try to make sure to don't lose it again. After a quick search on the web I found another version, that's here [The Pomodoro Technique](http://friend.ucsd.edu/reasonableexpectations/downloads/Cirillo%20--%20Pomodoro%20Technique.pdf).

Probably we should download and add that PDF as part of this repository. What do you think? The paper is released under _Creative Commons Attribution-Noncommercial-No Derivative Works 3.0 License_, so we are allowed to copy and redistribute it with no changes.

Would you like to update this PR? We might put the PDF under an `assets/` folder. Something like: `assets/the-pomodoro-technique.pdf`.

**Comment by Zilnik** [comment]
Hi @joebew42,

great idea. Added the pdf to the assets folder.

**Comment by joebew42** [comment]
> great idea. Added the pdf to the assets folder.

Great! Eh eh, we are not going to lose it again :+1:

Just a small nitpick, maybe better if we rename the file using a lower case, with no space convention. Something like: `the-pomodoro-technique.pdf`. What do you think?

I am really happy to merge this PR! :tada:

**Review by joebew42 — APPROVED** [review]
Awesome! It looks great :tada: Thanks again for this contribution :clap:

**Pull request merged**
